services:
  mongo:
    image: mongo:6.0
    container_name: my-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  flask-app:
    build: .
    container_name: SFTP-Mesh-Monitor
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - mongo
    command: ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]

volumes:
  mongo_data: